### ISSUE TITLE
Unify /Status and /status folders

### ISSUE THREAD

**Issue by toddysm** [agitaretech/nsc-cloudproject-s22016#8]
@jbauti02 Please move your statuses to the /status (lowercase only) folder and remove the /Status (uppercase S).

**Comment by jbauti02** [comment]
ok

**Comment by jbauti02** [comment]
hey Toddy i renamed my folder like u said from my github desktop, commited
it and synced it, did a pull request but its not showing the change online
but i think if approved the change will take effect, im still new at
github, please let me know if you need anything thanks.
- Joaquin
